language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "uorder"
  - git config user.email "cryink@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GHTOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - markdown
env:
 global:
   - GH_REF: github.com/zhaoyin/zhaoyin.github.io.git
